
import {
  LayoutDashboard,
  Rocket,
  Layers,
  Bot,
  ScrollText,
  Settings,
  Github,
  ChevronRight,
  LogOut,
  CheckCircle2,
  XCircle,
  Loader,
  Copy,
  Plus,
  ArrowRight,
  Send,
  Code,
  Box,
  Wrench,
  PackageCheck,
  Menu,
  ArrowLeft,
  Key,
  Info,
  AlertTriangle,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  NewDeployment: Rocket,
  Deployments: Layers,
  DevAI: Bot,
  Logs: ScrollText,
  Settings: Settings,
  GitHub: Github,
  ChevronRight: ChevronRight,
  Logout: LogOut,
  CheckCircle: CheckCircle2,
  XCircle: XCircle,
  Spinner: Loader,
  Copy: Copy,
  Plus: Plus,
  ArrowRight: ArrowRight,
  Send: Send,
  Code: Code,
  Box: Box,
  Wrench: Wrench,
  Package: PackageCheck,
  Menu: Menu,
  ArrowLeft: ArrowLeft,
  Key: Key,
  Info: Info,
  AlertTriangle: AlertTriangle,
};